CMakeLists.txt
skyrim-platform/CMakeLists.txt

Allow passing backslashes to SKYRIM_DIR

---

skymp5-server/cpp/server_guest_lib/IDatabase.h

In a reaction to #70. PRs like this would be merged periodically.

Improve code readability

---

skymp5-server/cpp/lib_espm/Combiner.h
skymp5-server/cpp/lib_espm/espm.cpp
skymp5-server/cpp/lib_espm/espm.h
skymp5-server/cpp/unit/EspmTest.h

tests(skymp5-server): unit tests for iterating GRUP children in lib_espm

---

docs/docs_server_configuration_reference.md

docs: describe startPoints setting

---

skymp5-server/cpp/lib_espm/Loader.cpp
skymp5-server/cpp/lib_espm/Loader.h
skymp5-server/cpp/lib_espm/ZlibUtils.h
skymp5-server/cpp/lib_espm/espm.cpp
skymp5-server/cpp/lib_espm/espm.h
skymp5-server/cpp/unit/EspmTest.cpp

Close #107
Some functional has been added to espm library which will help in #118

feat(skymp5-server): check CRC32 of esm files

---

skymp5-server/cpp/server_guest_lib/IPapyrusClass.h
skymp5-server/cpp/server_guest_lib/WorldState.cpp

fix(skymp5-server): memory leak in WorldState::GetPapyrusVm

---

.github/workflows/pr-windows.yml
CMakeLists.txt
unit/CMakeLists.txt
unit/main.cpp

internal: test espm in CI

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp
skymp5-server/cpp/server_guest_lib/MpChangeForms.cpp
skymp5-server/cpp/server_guest_lib/MpChangeForms.h
unit/ActorTest.cpp
unit/SaveStorageTest.cpp

feat(skymp5-server): add attribute percentages to MpChangeFormREFR

---

skymp5-client/src/front/components/actorvalues.ts
skymp5-client/src/front/messages.ts
skymp5-client/src/front/skympClient.ts
skymp5-client/src/lib/structures/actorvalues.ts

feat(skymp5-client): send changed attribute percentages to the server

---

skymp5-client/src/front/deathSystem.ts
skymp5-client/src/front/skympClient.ts

feat: use startDeferredKill to prevent player from unexpected death client-side 

---

skymp5-functions-lib/src/types/mp.d.ts
skymp5-server/cpp/addon/main.cc

- Addded new function "writeDataFile"

feat(skymp5-server): add writeDataFile function to gamemode API

---

skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt

- add enum for key codes
- add enum for ui event
information took from official site 
https://www.creationkit.com/index.php?title=Input_Script
https://www.creationkit.com/index.php?title=UI_Script

feat(skyrim-platform): add enums for key codes and menus

---

skyrim-platform/tools/plugin-example/README.md

closes #231 
Update Readme to be more clear on how to start with SkyrimPlatform

docs: update SP plugin example readme

---

docs/docs_server_command_line_api.md
docs/docs_server_configuration_reference.md
skymp5-server/ts/index.ts
skymp5-server/ts/settings.ts
skymp5-server/ts/systems/login.ts

feat(skymp5-server): add offline mode

---

.github/workflows/pr-windows.yml
CMakeLists.txt
chakra-wrapper/JsEngine.h
unit/CMakeLists.txt

internal: remove JsEngine tracing from GitHub builds

---

skymp5-server/cpp/server_guest_lib/ActionListener.cpp
unit/HitTest.cpp

feat(skymp5-server): check weapon existence before damage

---

skymp5-front/src/constructor.js
skymp5-front/src/constructorComponents/chat/index.js

fix(skymp5-front): fix keys and chat

---

docs/release/dev/add-enums.md
docs/skyrim_platform/new_events.md
docs/skyrim_platform/new_types.md
skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt

New enum based on https://www.creationkit.com/index.php?title=Slot_Masks_-_Armor
Already added documentation and release notes to it.

feat(skyrim-platform): add SlotMask enum

---

.gitmodules

Just updated submodule revision to fix https://github.com/microsoft/vcpkg/issues/18791
closes #80

internal: update vcpkg version

---

docs/docs_skyrim_platform.md
docs/skyrim_platform/cookbook.md
docs/skyrim_platform/new_events.md

Added the basis for a Cook Book to SP documentation.
Right now it only has two recipes. 
More to come in the future.

docs: add Skyrim Platform Cook Book

---

skymp5-client/src/actorvalues.ts
skymp5-client/src/deathSystem.ts
skymp5-client/src/index.ts
skymp5-client/src/messages.ts
skymp5-client/src/movement.ts
skymp5-client/src/msgHandler.ts
skymp5-client/src/networking.ts
skymp5-client/src/remoteServer.ts
skymp5-client/src/skympClient.ts
skymp5-server/cpp/mp_common/MsgType.h
skymp5-server/cpp/server_guest_lib/MpActor.cpp
skymp5-server/cpp/server_guest_lib/MpActor.h
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/MpObjectReference.h
unit/RespawnTest.cpp

feat: add respawn message

---

docs/release/dev/sp-add-hook-remove-method.md
docs/skyrim_platform/events.md
skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt
skyrim-platform/src/platform_se/skyrim_platform/EventsApi.cpp

feat(skyrim-platorm): add hook remove method

---

docs/release/dev/sp-add-plugins-dev-directory.md
docs/skyrim_platform/features.md
skyrim-platform/src/platform_se/skyrim_platform/DevApi.cpp
skyrim-platform/src/platform_se/skyrim_platform/DevApi.h
skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.cpp
skyrim-platform/tools/plugin-example/tsc/on-success.js

feat(skyrim-platform): add PluginsDev directory

---

docs/skyrim_platform/cookbook.md
docs/skyrim_platform/new_events.md
docs/skyrim_platform/new_methods.md

I also alphabetically sorted the links at the bottom of each page.
Those are the so called "deletions".

docs: add plugin initialization recipe

---

skymp5-server/cpp/lib_espm/Combiner.cpp
skymp5-server/cpp/lib_espm/Combiner.h
skymp5-server/cpp/server_guest_lib/ActionListener.cpp
skymp5-server/cpp/server_guest_lib/FindRecipe.cpp
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/PartOne.cpp
skymp5-server/cpp/server_guest_lib/WorldState.cpp
unit/CraftTest.cpp
unit/LoadCellsTest.cpp

fix(skymp5-server): fix DLC objects streaming

---

.github/workflows/deploy.yml
.github/workflows/pr-ubuntu-docker.yml
ci/deploy/call_webhook.sh
ci/deploy/push_branch_to_server.sh
ci/deploy/remote/pull_branch.sh
ci/deploy/workaround_temporary/run.sh
docs/docs_deploy.md

 internal: deploy to the sever via ssh

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp

feat(skymp5-server): add ability to cancel respawn in onDeath handler

---

skymp5-client/CMakeLists.txt
skymp5-front/CMakeLists.txt
skymp5-functions-lib/CMakeLists.txt
skymp5-server/ts/CMakeLists.txt
skyrim-platform/src/platform_se/CMakeLists.txt

internal: fix Windows CI

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp
skymp5-server/cpp/server_guest_lib/MpActor.h
skymp5-server/cpp/server_guest_lib/MpChangeForms.cpp
skymp5-server/cpp/server_guest_lib/MpChangeForms.h
skymp5-server/cpp/server_guest_lib/PartOne.cpp
unit/ActorTest.cpp
unit/RespawnTest.cpp

refact(skymp5-server): fix respawn point & respawn time

---

docs/release/dev/sp-array-returns.md
skyrim-platform/src/platform_se/skyrim_platform/CallNative.cpp
skyrim-platform/src/platform_se/skyrim_platform/CallNative.h
skyrim-platform/src/platform_se/skyrim_platform/NativeValueCasts.cpp

feat(skyrim-platform): support array return values in scripting functions

---

skymp5-functions-lib/src/types/mp.d.ts

Just set isDead type to boolean. 🙂

fix(skymp5-functions-lib): fix isDead property type

---

skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp
skyrim-platform/src/platform_se/skyrim_platform/FridaHooksUtils.cpp
skyrim-platform/src/platform_se/skyrim_platform/FridaHooksUtils.h
skyrim-platform/src/platform_se/skyrim_platform/main.cpp

Optionaly change png cursor coordinate source from memory to swf variables.
Switch flag kRunnnigAE hardcoded to false for now.

feat(skyrim-platform): add option to draw cursor without reverse

---

skymp5-server/cpp/server_guest_lib/PapyrusDebug.h

feat(skymp5-server): implement Debug.MessageBox

---

skymp5-functions-lib/index.ts
skymp5-server/cpp/server_guest_lib/PapyrusActor.h

feat: add missing Papyrus funcs

---

README.md

docs: mention ci/CreateArchive_SkyrimPlatform.cmd in readme

---

.github/workflows/pr-windows.yml

internal: unfreeze artifact-upload version

---

skymp5-client/src/view.ts

fix(skymp5-client): remove frame loss in sync

---

ci/deploy/push_branch_to_server.sh
skymp5-server/CMakeLists.txt
unit/DistContentsExpected.json

internal: add package.json and yarn.lock to server dist

---

skymp5-server/CMakeLists.txt

partially revert 7a5cd9acb0ba2f6aa9cc87e7baaff52840d50f39

internal: fix server launch script

---

skymp5-functions-lib/src/sweetPie.test.ts
skymp5-functions-lib/src/sweetPie.ts

fix(skymp5-functions-lib): don't give score on kill during warmup

---

skymp5-functions-lib/src/sweetPie.test.ts
skymp5-functions-lib/src/sweetPie.ts

fix(skymp5-functions-lib): reset round when all players have left

---

skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp

Closes #654 
Remove g flag. Set opacity to 0/100 every render call.

fix(skyrim-platform): fix cursor doubling

---

skyrim-platform/src/platform_se/skyrim_platform/TESEventEmitter.cpp
skyrim-platform/src/platform_se/skyrim_platform/TESEventEmitter.h

This PR add Event Emitter class, that containt methods to trigger events sinks.

feat(skyrim-platform): add ability to trigger event sinks

---

overlay_ports/chakracore/portfile.cmake
overlay_ports/chakracore/vcpkg.json

This PR is created to sync ChakraCore portfile with vcpkg PR https://github.com/microsoft/vcpkg/pull/22439

internal: refactor chakracore portfile

---

.github/workflows/deploy.yml
ci/deploy/remote/branchctl.sh
ci/deploy/workaround_temporary/run.sh

internal: fix deploy scripts

---

skymp5-client/src/authSystem.ts

feat(skymp5-client): add a setting to specify a custom master API

---

skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.cpp

fix(skyrim-platform): revert SP change introduced by auth PR

---

skymp5-front/.eslintrc.js
skymp5-front/package.json
skymp5-front/src/App.js
skymp5-front/src/components/SkyrimHint/SkyrimHint.scss
skymp5-front/src/constructor.js
skymp5-front/src/constructorComponents/chat/index.js
skymp5-front/src/constructorComponents/text/styles.scss
skymp5-front/src/globals.d.ts
skymp5-front/src/index.js
skymp5-front/src/interfaces/buttons.ts
skymp5-front/src/interfaces/inputs.ts
skymp5-front/src/utils/Widgets.js

`widgets.set` now doesn't break chat input

fix(skymp5-front): improve chat compatibility to widgets.set

---

docs/docs_running_a_server.md
skymp5-server/ts/publicIp.ts
skymp5-server/ts/systems/login.ts
skymp5-server/ts/systems/masterClient.ts

fix(skymp5-server): switch to another IP detection API

---

skymp5-server/cpp/CMakeLists.txt

~8.5 seconds faster on my machine

internal: speed up project files generation

---

skymp5-server/cpp/addon/main.cc
skymp5-server/ts/index.ts
skymp5-server/ts/scampNative.ts
skymp5-server/ts/systems/masterClient.ts

feat(skymp5-server): redirect NodeJS logs to spdlog

---

skymp5-client/src/index.ts
skymp5-client/src/view.ts

closes #820 and fix npc cleaner which not working in auth mode

fix(skymp5-client): fix bug when nicknames render when other player is behind

---

skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts

Also fixes the ability to return from an exit door to the lobby in case if player isn't in that round.

fix(skymp5-functions-lib): disable round actions confirmation

---

skymp5-client/src/view.ts

fix(skymp5-client): fix nickname "unordered_map" error

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp

1) add missing pie ids
2) ignore unknown actor values when eating items

fix(skymp5-server): fix pie script for other kinds of pies

---

skymp5-front/src/constructorComponents/chat/index.js

fix(skymp5-front): fix colored chat messages

---

skymp5-client/src/index.ts

feat(skymp5-client): remove weather control

---

skymp5-client/src/authSystem.ts
skymp5-client/src/index.ts

feat(skymp5-client): prevent character movement during auth

---

skymp5-server/cpp/server_guest_lib/PapyrusObjectReference.cpp

feat(skymp5-server): support formlists in AddItem/RemoveItem

---

README.md

Some components wants python on windows cmake configuration stage.

docs: add python to windows prerequisites

---

skymp5-server/cpp/server_guest_lib/PapyrusObjectReference.cpp

feat(skymp5-server): support passing FormList to ObjectReference.GetItemCount

---

skymp5-client/src/authSystem.ts
skymp5-client/src/browser.ts

Changed the interaction with the browser on the client a little using the new functionality `browser.IsFocused()` and `browser.isVisible()`
This will simplify the interaction with the browser. There will be no need to use variables such as 'browserVisibleState' and create functions to process them

refact(skymp5-client): improve interaction with browser

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp

closes all problems (closes #875)

fix(skymp5-server): fix inability to eat Snowberry Crostata

---

skyrim-platform/src/platform_se/skyrim_platform/CallNative.cpp
skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.cpp
skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.h
skyrim-platform/src/platform_se/skyrim_platform/main.cpp
vcpkg.json

Should help with skyrim-multiplayer/skymp#653

fix(skyrim-platform): execute game functions in game thread

---

skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts
skyrim-platform/tools/dev_service/index.js

Add type definitions to repo for extarnal usage.
Dev Service watch script copy `skyrimPlatform.ts` to codegen/convert-files dir now.

internal: add skyrimPlatform.ts to repo

---

docs/docs_server_configuration_reference.md
skymp5-functions-lib/index.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts

feat(skymp5-functions-lib): make a minimum threshold for starting a round

---

skymp5-client/src/authSystem.ts
skymp5-client/src/browser.ts
skymp5-client/src/index.ts
skymp5-front/src/index.js

closes #837, closes #874, closes #896

fix: browser and client auth issues

---

skymp5-functions-lib/index.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
skymp5-functions-lib/src/logic/SweetPieRound.test.ts
skymp5-functions-lib/src/logic/SweetPieRound.ts

feat(skymp5-functions-lib): reset spawnpoint on player disconnect

---

skymp5-functions-lib/src/logic/PlayerController.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
skymp5-functions-lib/src/logic/TestUtils.ts
skymp5-functions-lib/src/mpApiInteractor.ts
skymp5-functions-lib/src/props/evalProperty.ts

feat(skymp5-functions-lib): rename portals to describe what they do

---

skymp5-functions-lib/index.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
skymp5-functions-lib/src/logic/SweetPieMap.ts
skymp5-functions-lib/src/logic/SweetPieRound.test.ts
skymp5-functions-lib/src/logic/SweetPieRound.ts

feat(skymp5-functions-lib): add more cities

---

skymp5-functions-lib/index.ts

added placeholder to register functions for papyrus
Nice thing to check scripts even without full implementation of papyrus library

feat(skymp5-functions-lib): placeholder function for papyrus

---

skymp5-client/src/view.ts

added hasLos (line of sight) and sneaking conditions for nicknames visibility

feat(skymp5-client): update nicknames visibility

---

skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts

feat(skymp5-functions-lib): reward winners with septims instead

---

skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt
skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts

https://github.com/skyrim-multiplayer/skymp/blob/072d06ed3050a47094c67bcf8ca4e549e221f601/skyrim-platform/src/platform_se/skyrim_platform/ConsoleApi.cpp#L323

feat(skyrim-platform): fix return type for findConsoleCommand

---

skymp5-functions-lib/src/mpApiInteractor.ts
skymp5-functions-lib/src/props/chatProperty.ts
skymp5-functions-lib/src/utils/functionInfo.ts

At least it became a bit better without custom arguments serialization...
Examples:
* `const {nameUpdatesJson} = {"nameUpdatesJson":[[100937665,"Скоро..."],[100937584,"Войти в десматч\nИгроков сейчас: 0 (мин 5 для старта игры)\nОжидание игроков..."],[100937535,"Выйти из игры и вернуться на рабочий стол"],[100937366,"Скоро..."]]};try{for(const[e,t]of nameUpdatesJson){const o=ctx.sp.ObjectReference.from(ctx.sp.Game.getFormEx(e)),r=null==o?void 0:o.setDisplayName(t,!0);r||ctx.sp.printConsole("setDisplayName failed:",t,o,r)}}catch(e){ctx.sp.printConsole('[CTX ERROR]', e, '\n', ()=>{for(const[e,t]of nameUpdatesJson){const o=ctx.sp.ObjectReference.from(ctx.sp.Game.getFormEx(e)),r=null==o?void 0:o.setDisplayName(t,!0);r||ctx.sp.printConsole("setDisplayName failed:",t,o,r)}})}`
* ```const …
```

refact(skymp5-functions-lib): simplify FunctionInfo

---

.github/workflows/pr-ubuntu-docker.yml
skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts

internal: check SP types

---

skymp5-client/src/view.ts

feat(skymp5-client): re-enable player activation

---

docs/docs_server_configuration_reference.md
skymp5-functions-lib/src/props/disableCheats.ts

Also fixes `tfc` and maybe something else

feat(skymp5-functions-lib): add config option to allow cheats

---

skymp5-client/src/deathSystem.ts

feat(skymp5-client): disable stagger animations

---

skymp5-functions-lib/index.ts
skymp5-functions-lib/src/logic/PlayerController.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
skymp5-functions-lib/src/logic/SweetPieRound.ts
skymp5-functions-lib/src/logic/TestUtils.ts
skymp5-functions-lib/src/mpApiInteractor.ts
skymp5-functions-lib/src/props/counterProperty.ts

feat(skymp5-functions-lib): reward all players with ingots on game end

---

skymp5-client/src/remoteServer.ts
skymp5-client/src/view.ts

this bug can make other player invulnerable

fix(skymp5-client): fix remote ref id and local ref id mismatch in some cases

---

skymp5-server/cpp/server_guest_lib/PartOne.cpp

Just checking if this is unit tested
UPD: yes

fix(skymp5-server): support huge base ids

---

skymp5-server/cpp/server_guest_lib/ActionListener.cpp
skymp5-server/cpp/server_guest_lib/PacketParser.cpp
unit/PartOne_ActivateTest.cpp

fix(skyrim5-server): make players able to put equipped items

---

skymp5-server/cpp/server_guest_lib/ConsoleCommands.cpp
unit/ConsoleCommandTest.cpp

Reverts skyrim-multiplayer/skymp#906

internal: revert deletion of console command tests

---

skymp5-server/cpp/lib_espm/espm.cpp
skymp5-server/cpp/lib_espm/espm.h
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
unit/PickUpItemCountTest.cpp

feat(skymp5-server): take items count into account when picking them up

---

.gitignore

Just added `.cache/` that is generated by clangd.

internal: update .gitignore

---

chakra-wrapper/JsEngine.h

Remove copyrighted code to be able to merge https://github.com/skyrim-multiplayer/skymp/pull/1054 without etherform approval (not sure I can contact currently).

refact(chakra-wrapper): remove JsEngine changes came from AE branch

---

.github/workflows/sp-release.yml

internal: fix pattern in changelog generation script

---

ROADMAP.md

docs: apply style and language fixes to ROADMAP.md

---

THIRD_PARTY_LICENSES

docs: add font licenses

---

1js/JsEngine.h

feat(1js): drop wstring/u16string support

---

CMakeLists.txt
CONTRIBUTING.md

internal: unsupport ONLY_SP build

---

skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt
skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts

fix(skyrim-platform): fix getExtraContainerChanges return type

---

docs/release/dev/sp-mo2-overwrite-issue.md
skyrim-platform/src/tilted/ui/MyChromiumApp.cpp

fix(skyrim-platform): fix MO2 overwrite issue

---

docs/release/dev/sp-bad-ae-dist.md

It's for fd68b22b9307f859b53a9faa4c29d8b2fced856b

docs: create a changelog for the recent change

---

skymp5-client/src/messages.ts
skymp5-client/src/skympClient.ts
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/PacketParser.cpp

feat: implement DropItem on client

---

skymp5-client/src/skympClient.ts

fix(skymp5-client): fix item dropping

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp
unit/DropItemTest.cpp

feat(skymp5-server): taking count into account on dropping

---

skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
skymp5-server/cpp/server_guest_lib/ActionListener.cpp
skymp5-server/cpp/server_guest_lib/MpActor.cpp

feat: update pies logic

---

skymp5-server/cpp/server_guest_lib/ConsoleCommands.cpp
unit/ConsoleCommandTest.cpp

feat(skymp5-server): update admins list

---

skymp5-front/src/constructorComponents/chat/index.js

~~**NEEDS TESTING BEFORE MERGING**~~ @SupAidmi said that everything is ok
This should fix some performance issues.

feat(skymp5-front): display only 50 last messages in chat

---

skymp5-client/src/features/browser.ts
skymp5-client/src/view/formView.ts

Hotkey changes:
F1 - hide\show nicknames,
F2 - hide\show browser,
Enter - open chat (focus browser)

feat(skymp5-client): add hotkey to toggle nicknames visiblity and change some others

---

skymp5-client/src/index.ts
skymp5-client/src/sweetpie/playerCombatSystem.ts

- temporary disable combat timitng
- remove some legacy code

feat(skymp5-client): temporary disable combat timitng

---

skymp5-front/package.json
skymp5-front/src/constructorComponents/chat/dices/index.tsx
skymp5-front/src/constructorComponents/chat/index.js
skymp5-front/src/constructorComponents/chat/styles.scss
skymp5-front/yarn.lock

feat(skymp5-front): make chat list resizable & focus input after click

---

skymp5-server/cpp/papyrus_vm_lib/ActivePexInstance.cpp
skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
skymp5-server/cpp/server_guest_lib/WorldState.cpp
skyrim-platform/src/platform_lib/Validators.cpp
skyrim-platform/src/platform_se/skyrim_platform/papyrus-vm-lib/Reader.cpp

Return false and assert(0) have been replaced with throw runtime_error()

Adding exception runtime_error()

---

skymp5-server/cpp/server_guest_lib/ActionListener.cpp
skymp5-server/cpp/server_guest_lib/ActionListener.h
skymp5-server/cpp/server_guest_lib/AnimationData.cpp
skymp5-server/cpp/server_guest_lib/AnimationData.h
skymp5-server/cpp/server_guest_lib/MpActor.cpp
skymp5-server/cpp/server_guest_lib/MpActor.h
skymp5-server/cpp/server_guest_lib/PacketParser.cpp

Implemented animation dependent block.
Closes #1174.

feat(skymp5-server): implement serverside animatinon dependent block

---

.github/workflows/deploy.yml
.github/workflows/formatting.yml
.github/workflows/pr-ubuntu-docker.yml
.github/workflows/pr-windows-ae.yml
.github/workflows/pr-windows.yml

internal: update some GH actions

---

skyrim-platform/src/tilted/ui/DX11RenderHandler.cpp
skyrim-platform/src/tilted/ui/DX11RenderHandler.h

internal: fix Windows build with modern DirectX libs

---

.github/workflows/pr-windows-ae.yml
.github/workflows/pr-windows.yml
cmake/link_vcpkg_dependencies.cmake
unit/DistContentsExpected.json

The way I did it in #1156 was wrong...

internal: replace system vcpkg on Windows CI

---

unit/HttpClientApiTest.cpp

discovered random failure in https://github.com/skyrim-multiplayer/skymp/pull/1255

tests: fix http test random failure

---

skymp5-client/src/features/worldCleaner.ts

See your bugs channel in Discord
Someone reports this bug in Riften jarl house

fix(skymp5-client): NPC appear unexpectedly

---

skymp5-functions-lib/LICENSE

closes #1274
This PR doesn't change the license, it's still the same as package.json has

internal: create license file

---

skymp5-server/cpp/server_guest_lib/ScriptStorage.cpp

Without this fix I have an error

internal: add missing header

---

ci/deploy/push_branch_to_server.sh

internal: fix libchakracore location in deploy script

---

misc/deploy/remote/branchctl.sh
misc/github_env_linux

Includes PR #1304, upstreamed as https://github.com/microsoft/vcpkg/pull/28769

internal: update vcpkg

---

docs/release/dev/sp-improve-plugins-detection.md
skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.cpp

fix(skyrim-platform): improve plugins detection

---

skymp5-client/src/extensions/timers.ts

sp.storage.foo is a function (very much like sp.game.getplayer is a function)

fix(skymp5-client): fix timers init

---

cmake/link_vcpkg_dependencies.cmake

internal: improve chakracore cmake clue

---

skymp5-client/src/sync/inventory.ts

tested logging in with 1 million items of type, putting in a container, taking from a container

fix(skymp5-client): improve inventory performance

---

skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp

feat(skymp5-server): add animation processing for left-handed attacks 

---

docs/docs_events_system.md
skymp5-server/cpp/addon/main.cc
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/MpObjectReference.h

feat(skymp5-server): remove unused events

---

skymp5-server/cpp/server_guest_lib/SweetPieScript.cpp

feat(skymp5-server): play weapon drawing animation when a player equips a bound one

---

skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp

fix(skymp5-server): fix picking up FLOR/TREE with LVLI ingredients

---

.gitignore

Small change to ignore VS files.
Potentially more VS-related PR's to come soon.

internal: add VS folder to .gitignore

---

docs/release/dev/sp-fixed-startup-crash.md
skyrim-platform/src/tilted/ui/MyChromiumApp.cpp

https://www.nexusmods.com/users/11314793
pending author's username+email or pull request to preserve authorship

fix(skyrim-platform): fix random startup crash related to Chromium

---

docs/release/dev/sp-fixed-cellattach-crash.md
skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp

fix(skyrim-platform): fix cellAttach/cellDetach crash

---

.github/workflows/build-vcpkg-deps.yml

ports this better
https://raw.githubusercontent.com/skyrim-multiplayer/skymp/9df63f4a2255e01eb9cbfe06400776cbd6db3d39/misc/build-docker-image.sh

internal: fix build-vcpkg-deps.yml to handle both images

---

skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp

feat(skymp5-server): decrease stamina on dual attack

---

cmake/apply_default_settings.cmake
skymp5-server/cpp/server_guest_lib/DynamicFields.cpp
skymp5-server/cpp/server_guest_lib/DynamicFields.h
skymp5-server/cpp/server_guest_lib/MpChangeForms.h
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/WorldState.cpp

1. nullptr passed to pImpl in ctor
2. invalidating unordered_map iterator

fix(skymp5-server): fix crash in changeforms load

---

docs/release/dev/sp-extend-texts-api.md

Now you can change the size, rotation, font, depth, effects and origin of the text.
- `setTextSize(textId: number, size: float)` - set text (not font) size.
- `setTextRotation(textId, rotation: float)` - set rotation.
- `setTextFont(textId, name: string)` - set font from relative path "Data/Platform/Fonts/", by name — "Tavern".
- `setTextDepth(textId, depth: int)` - set z-index of the text.
- `setTextEffect(textId, effect: skyrimPlatform.SpriteEffects)` - set sprite effect [None = 0, FlipHorizontally = 1, FlipVertically = 2]
- `setTextOrigin(textId, origin: [x,y])` - set text pivot (center point).
>To use your own font, upload .sprite version to the "/Data/Platform/Fonts/" folder and call by name WITHOUT extension
> How to convert any font to .sprite, you can find in the [Special docs …

docs: add change-log for TextsAPI update

---

skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp

Reverts skyrim-multiplayer/skymp#1505

fix(skyrim-platform): revert "fix containerChanged event crash"

---

docs/release/dev/sp-fix-events-handling.md
skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp

Reverts skyrim-multiplayer/skymp#1496

fix(skyrim-platform): revert "improve event handlers safety"

---

skymp5-functions-lib/src/logic/listeners/harvestingSystem/index.ts

as blockActivation not working atm we can leave continue for each return

fix(skymp5-functions-lib): change blockActivation to continue in harvesting module

---

skymp5-server/cpp/server_guest_lib/ActionListener.cpp

now we can not update other players movement locally
discovered while experimenting with bots

fix(skymp5-server): fix vulnerability in ActionListener.cpp

---

skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp

Reverts skyrim-multiplayer/skymp#1534

fix(skymp5-server): revert "stop passing double activation to Papyrus"

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp

fix(skymp5-server): consumable items are being added back to the inventory

---

docs/release/dev/sp-fix-combatState-crash.md
skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp

Follow the example of the fix for #1305.
closes #1544

fix(skyrim-platform): fix crash in combatState event

---

docs/release/dev/sp-fix-truehud-spriggan.md
skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp

fix(skyrim-platform): fix spriggan and TrueHUD related crash

---

skymp5-server/cpp/server_guest_lib/MpChangeForms.h

fix(skymp5-server): fix MpChangeForm::ToTuple to respect learnedSpells #1559

---

skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp

fix(skymp5-server): ignore occupant if player is offline (disabled)

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp
skymp5-server/cpp/server_guest_lib/MpActor.h

fix(skymp5-server): do not remove books that do not contain spells on reading

---

libespm/include/libespm/LIGH.h
libespm/include/libespm/Records.h
libespm/src/LIGH.cpp
libespm/src/Utils.cpp
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
unit/PartOne_ActivateTest.cpp

feat(skymp5-server): implement activate processing for torches

---

.github/workflows/deploy.yml

Reverts skyrim-multiplayer/skymp#1628

internal: revert "configure sweettaffy nightly deploy"

---

skymp5-server/cpp/server_guest_lib/ActionListener.cpp
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/MpObjectReference.h

---
- https://app.asana.com/0/0/1205164194490627

perf(skymp5-server): save actor listeners separately

---

skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp

---
- https://app.asana.com/0/0/1205159562441222

feat(skymp5-server): add log for activate

---

docs/docs_server_configuration_reference.md
skymp5-server/cpp/addon/ScampServer.cpp
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/WorldState.cpp
skymp5-server/cpp/server_guest_lib/WorldState.h

---
- https://app.asana.com/0/0/1205164194080463

feat(skymp5-server): add config settings that restricts reloot for specific items based on their record type

---

skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp
skymp5-server/cpp/server_guest_lib/CropRegeneration.cpp
skymp5-server/cpp/server_guest_lib/MpActor.cpp

---
- https://app.asana.com/0/0/1205195058410685

fix(skymp5-server): set ActorValues from the game files

---

docs/release/dev/sp-fix-chromium-up-down-keys.md
skyrim-platform/src/platform_se/skyrim_platform/main.cpp

fix(skyrim-platform): up-down keys mapping

---

skymp5-client/src/services/sendInputsService.ts

---
- https://app.asana.com/0/0/1205197656218036

fix(skymp5-client): make regen unreliable and less often

---

skymp5-server/cpp/server_guest_lib/ActionListener.cpp
skymp5-server/cpp/server_guest_lib/FormCallbacks.h
skymp5-server/cpp/server_guest_lib/MpActor.cpp
skymp5-server/cpp/server_guest_lib/MpActor.h
skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
skymp5-server/cpp/server_guest_lib/PartOne.cpp
skymp5-server/cpp/server_guest_lib/PartOne.h
skymp5-server/cpp/server_guest_lib/ServerState.h
unit/ConsoleCommandTest.cpp
unit/DropItemTest.cpp
unit/PartOne_ActivateTest.cpp

---
- https://app.asana.com/0/0/1205262546944373

fix(skymp5-server): implement bulk inventory updates

---

skymp5-server/package.json
skymp5-server/yarn.lock

fixes deasync build on some linux distros

internal: update skymp5-server ts deps

---

skymp5-server/package.json
skymp5-server/yarn.lock

unused these days but requires lots of node-gyp stuff

internal: remove parcel-bundler dependency

---

skymp5-server/cpp/server_guest_lib/SweetPieBoundWeapon.cpp
skymp5-server/cpp/server_guest_lib/SweetPieBoundWeapon.h
skymp5-server/cpp/server_guest_lib/SweetPieScript.cpp
skymp5-server/cpp/server_guest_lib/SweetPieScript.h

requires testing by @Ansgar-skymp 
---
- https://app.asana.com/0/0/1205307434172616

feat(skymp5-server): add more conjured weapons

---

CONTRIBUTING.md
Dockerfile
docs/docs_deploy.md

updated ubuntu version in Dockerfile
removed useless apt packages (linux-tools) (skymp builds successfully without it)
updated ubuntu version in docs

internal: update ubuntu version

---

CONTRIBUTING.md
Dockerfile
docs/docs_deploy.md

Reverts skyrim-multiplayer/skymp#1678

internal: revert "update ubuntu version"

---

skyrim-platform/src/platform_se/skyrim_platform/TextApi.cpp
skyrim-platform/src/platform_se/skyrim_platform/TextsCollection.cpp
skyrim-platform/src/platform_se/skyrim_platform/TextsCollection.h
skyrim-platform/src/platform_se/skyrim_platform/main.cpp

Reverts skyrim-multiplayer/skymp#1515
crashes on Ansgar's and Supaidmi's machine when connecting to the server

fix(skyrim-platform) revert "optimize texts collection"

---

docs/release/dev/sp-fix-cameraStateChanged-event-crash.md
skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp

fix(skyrim-platform): fix crash in cameraStateChanged event

---

vcpkg.json

reverting bad upstream update https://github.com/microsoft/vcpkg/pull/33182

fix: skymp client crashes after 15 seconds in game

---

skymp5-server/cpp/server_guest_lib/MpActor.cpp
skymp5-server/cpp/server_guest_lib/MpActor.h
skymp5-server/cpp/server_guest_lib/MpChangeForms.cpp
skymp5-server/cpp/server_guest_lib/MpChangeForms.h
skymp5-server/cpp/server_guest_lib/script_classes/PapyrusActor.cpp
skymp5-server/cpp/server_guest_lib/script_classes/PapyrusActor.h

also adds missing WornHasKeyword registration

feat(skymp5-server): implement AddSpell/RemoveSpell Papyrus methods

---

skymp5-front/src/constructorComponents/chat/index.js

Somehow can't catch up and down arrows pressing...
Now it's binded to arrow left and arrow right
Will look into using up and down arrors....

feat(skymp5-front): add chat history

---

skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp
skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.h

https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUIcmlja3JvbGw%3D

feat(skymp5-server): implement some natives from recent Skyrim updates

---

skymp5-front/src/constructorComponents/chat/index.js

Reverts skyrim-multiplayer/skymp#1571
it works but users don't like that feature
they want navigation in multiline messages with up/down
reverting for now.

feat(skymp5-front): revert "add chat history"

---

skymp5-front/src/constructorComponents/chat/index.js

Reverts skyrim-multiplayer/skymp#1763

feat(skymp5-front): revert "revert "add chat history""

---

skymp5-server/cpp/server_guest_lib/formulas/TES5DamageFormula.cpp

@Pospelove, Aidmi asked me to add this. There's also a little improvement in readability, at least as I think.

fix(skymp5-server): decrease unarmed damage if the hit was blocked

---

skymp5-client/src/services/events/events.ts
skymp5-client/src/services/events/queryBlockSetInventoryEvent.ts
skymp5-client/src/services/services/playerBowShotService.ts
skymp5-client/src/services/services/remoteServer.ts

follow up https://github.com/skyrim-multiplayer/skymp/pull/1849

fix(skymp5-client): remove ammo on crossbow shots as well

---

.github/workflows/deploy.yml

Reverts skyrim-multiplayer/skymp#1941

internal: revert "fix deploy.yml"

---

.github/workflows/deploy.yml

otherwise skymp-5-fnctions-lib/cmakelists.txt will not be able to detect those vars

internal: propagate some env vars to configure container

---

skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp

This is fixed manually by me during the private talk with SupAidmi in Discord. And is used for the follow up PR which is generated.

fix(skyrim-platform): fix more crashes in events

---

skymp5-client/src/sync/equipment.ts

likely related to 1170 version of the game

fix(skymp5-client): fix inability to unequip items

---

docs/docs_properties_system.md

Reverts skyrim-multiplayer/skymp#1999

docs: revert "document isDead property caveats"

---

misc/tests/test_isdead.js

this is a testing gamemode 
TODO: connect to CTest

internal: commit test_isdead.js

---

skyrim-platform/src/platform_se/skyrim_platform/TextApi.cpp
skyrim-platform/src/platform_se/skyrim_platform/TextsCollection.cpp
skyrim-platform/src/platform_se/skyrim_platform/TextsCollection.h
skyrim-platform/src/platform_se/skyrim_platform/main.cpp

Reverts skyrim-multiplayer/skymp#1701

fix(skyrim-platform): revert "optimize texts collection"

---

docs/docs_database_drivers.md
skymp5-server/cpp/CMakeLists.txt
skymp5-server/cpp/server_guest_lib/database_drivers/DatabaseFactory.cpp
skymp5-server/cpp/server_guest_lib/database_drivers/ZipDatabase.cpp
skymp5-server/cpp/server_guest_lib/database_drivers/ZipDatabase.h
skymp5-server/cpp/server_guest_lib/save_storages/AsyncSaveStorage.cpp
skymp5-server/cpp/server_guest_lib/save_storages/AsyncSaveStorage.h
skymp5-server/cpp/server_guest_lib/save_storages/ISaveStorage.h
unit/SaveStorageTest.cpp
vcpkg.json

initially used that driver for mongodb cache in https://github.com/skyrim-multiplayer/skymp/pull/2026
However, I decided that original PR is bad and must never be accepted. However, the driver itself is functional and unit tested so I decided to put it here.

feat(skymp5-server): add zip database driver

---

skymp5-client/src/services/services/authService.ts

they were not really ms they were seconds. fix that

fix(skymp5-client): increase delays in AuthService

---

.github/workflows/deploy.yml
.github/workflows/formatting.yml
.github/workflows/pr-emscripten.yml
.github/workflows/pr-macos.yml
.github/workflows/pr-ubuntu-docker.yml
.github/workflows/pr-windows-skyrim-ae.yml
.github/workflows/pr-windows-skyrim-se.yml
.github/workflows/prettier.yml
.github/workflows/push-skymp5-patches.yml
.github/workflows/sp-release.yml

internal: update actions/checkout and actions/upload-artifact
