skyrim-multiplayer/skymp

docs/docs_database_drivers.md, docs/docs_running_a_server.md, docs/docs_server_configuration_reference.md
Using `json5` syntax instead of `json` will not highlight comments in red
=> docs: fix highlighting in running server docs

CMakeLists.txt
Actually, Clang does not even have this option. Other compilers are not supported currently due to Chakracore restrictions.
=> Remove -fpermissive compiler option

CMakeLists.txt, chakra-wrapper/CMakeLists.txt, skymp5-server/cpp/CMakeLists.txt, skyrim-platform/src/platform_se/CMakeLists.txt
One of our devs (@bogdasar1985) is able to reproduce the issue linking `chakra-wrapper`. Instead of linking interface target properly (by adding include path), it attempts to perform real linking. It thinks there is a shared library called `chakra-wrapper`.
This PR removes this target in order to fix the issue. Instead of using an interface target we just use `target_include_directories`.
=> internal: fix chakra-wrapper linking on Linux

skymp5-server/cpp/unit/DistContentsExpected.json, skymp5-server/cpp/unit/DistContentsTest.h
When building Debug and then Release, dist is not being cleaned so `scamp_native.ilk` may stay and ruin unit tests (DistContentsTest.h)
=> tests: stop checking scamp_native.ilk in distribution

skyrim-platform/src/platform_se/skyrim_platform/PapyrusTESModPlatform.cpp
closes #143
After internal discussion, we decided that error handling itself isn't implemented properly here: it's unexpectedly hard to understand what's going on when the `Missing files` error is thrown. But that's out of the scope of this PR, it's more like a **hotfix**. Hope we can merge it as soon as possible. We can not distribute Skyrim Platform until this fix is integrated.
=> fix(skyrim-platform): plugins didn't work without WorldSpace.pex installed

docs/docs_maintainer_rules.md
It seems that our naming convention doesn't allow us to give a reasonable name to #149
I think introducing `refact` commit type solves this problem.
=> docs: add refact commit type

skymp5-server/cpp/addon/main.cc, skymp5-server/cpp/server_guest_lib/ActionListener.cpp, skymp5-server/cpp/server_guest_lib/DummyWorldObject.h, skymp5-server/cpp/server_guest_lib/FormDesc.cpp, skymp5-server/cpp/server_guest_lib/FormDesc.h, skymp5-server/cpp/server_guest_lib/IWorldObject.h, skymp5-server/cpp/server_guest_lib/MovementValidation.cpp, skymp5-server/cpp/server_guest_lib/MovementValidation.h, skymp5-server/cpp/server_guest_lib/MpActor.cpp, skymp5-server/cpp/server_guest_lib/MpActor.h, skymp5-server/cpp/server_guest_lib/MpChangeForms.cpp, skymp5-server/cpp/server_guest_lib/MpChangeForms.h, skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp, skymp5-server/cpp/server_guest_lib/MpObjectReference.h, skymp5-server/cpp/server_guest_lib/PartOne.cpp, skymp5-server/cpp/server_guest_lib/WorldState.cpp, unit/CraftTest.cpp, unit/MovementValidationTest.cpp, unit/ObjectReferenceTest.cpp, unit/PapyrusCompatibilityTest.cpp, unit/PartOne_ActivateTest.cpp, unit/PartOne_ActorTest.cpp, unit/RespawnTest.cpp, unit/WorldStateTest.cpp
closes #50 
1. You can now activate objects in non-Skyrim.esm world spaces.
2. Save files now using `formDesc` instead of `formId` to store your current world space.
**Warning! Old save files are incompatible.**
=> fix(skymp5-server): improve DLC worldspaces support

skymp5-client/src/browser.ts, skymp5-client/src/remoteServer.ts
1. Do not keep player reference across async operations.
2. Shittify code a bit in `browser.ts` to prevent `Unsupported JavaScript type (6)` error (reproduced by killing myself too). By the right of skymp's maintainer, I merge my shitty code piece to see if it really helps. After shittifying the code I wasn't able to reproduce the bug.
=> fix(skymp5-client): respawn didn't work in SweetPie world

.editorconfig, CMakeLists.txt, skymp5-server/CMakeLists.txt, skymp5-server/cpp/CMakeLists.txt, skymp5-server/package.json
Changes:
- Use system-wide `vcpkg` by default if it's installed and configured correctly.
- Changed some deprecated library naming in server's cmake
- Force `cmake-js` to use `-G "Visual Studio 16 2019"`, which fixes build error which pops if VS 2022 build tools are installed alongside. Might not be the best option, especially if Linux build support is required.
closes #80
=> internal: some minor build fixes

skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp, skyrim-platform/src/platform_se/skyrim_platform/FridaHooksUtils.cpp, skyrim-platform/src/platform_se/skyrim_platform/FridaHooksUtils.h, skyrim-platform/src/tilted/ui/DX11RenderHandler.cpp
closes #506 
This little patch changes the behaviour of rendering custom png cursor.
Before: sp redraws cursor with custom all the time
After: cursor swtiched to png only in case of browser focused and visible
The reason why we need this two flags is that people can use broswer in "widget" mode.
=> fix(skyrim-platform): change behavior of cursor render

skymp5-server/cpp/lib_espm/espm.cpp
Fixes this warning:
```
/src/skymp5-server/cpp/lib_espm/espm.cpp:1101:55: warning: adding 'const char' to a string does not append to the string [-Wstring-plus-int]
throw std::runtime_error("Bad effect array. " + *name);
~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```
=> fix(skymp5-server): fix error in log message forming

.github/workflows/deploy.yml, .github/workflows/pr-ubuntu-docker.yml
`scamp_native.node` became a bit more of a size (34.9 MiB -> 40.6 MiB), but the builds are now both optimized (`-O2`) and have debug info (`-g`):
```json5
[
{
"directory": "/src/build/viet",
"command": "/usr/bin/clang++-12  -I/src/viet/src -I/src/viet/include -O2 -g -DNDEBUG -fPIC -std=c++17 -o CMakeFiles/viet.dir/src/Promise.cpp.o -c /src/viet/src/Promise.cpp",
"file": "/src/viet/src/Promise.cpp"
},
...
]
```
=> internal: make Linux builds RelWithDebInfo

skyrim-platform/tools/plugin-example/webpack.config.js
Change webpack of the plugin-example to use mode: development instead of mode: production.
With mode: production, the code is minified to one line making debugging runtime .js errors pretty much impossible.
=> refact(skyrim-platform): configure webpack for development mode

skymp5-client/CMakeLists.txt, unit/DistContentsExpected.json
This PR follows https://github.com/skyrim-multiplayer/skymp/pull/388
The original PR drops legacy functionality. My PR cleans build system 
TODO: merge this to indev after shipping #722 and then test and merge
=> internal: remove skymp5-client.js from server dist

skymp5-server/cpp/addon/main.cc
Sometimes you have to execute client code from the api.
In functions-lib we use eval function
```ts
static eval(actorId: number, f: (ctx: Ctx, ...args: any[]) => void, args?: Record<string, unknown>) {
const code = new FunctionInfo(f).getText(args);
const value: EvalValue = mp.get(actorId, 'eval') || { commands: [], nextId: 0 };
value.commands.push({ code, id: value.nextId });
value.nextId++;
mp.set(actorId, 'eval', value);
}
```
but this method requires the conversion of the function into a string and then execution via eval, which is not good, as it seems to me
I propose to describe the logic of the client function in skymp5-client. And when we send a packet like this
```ts
mp.sendCustomPacket(selfId, { type: 'function', name: 'equipItem', data: { itemId, preventRemoval, silent } })
``` …
=> feat(skymp5-server): add sendCustomPacket method to mp api

build.sh
Turns out `.git` in the repository root can be a regular file if we deal with secondary working trees: \
https://stackoverflow.com/a/30185564
=> internal: allow .git to be a file in build.sh

.github/workflows/deploy.yml, Dockerfile, ci/deploy/push_branch_to_server.sh, ci/deploy/remote/branchctl.sh, docs/docs_deploy.md
closes #883
Things that are done in this PR (or along with it):
1. Fix for stuck `timeout 5m docker logs -f ... |& grep -q ...`. It is a bit ugly, but is apparently more stable.
2. Separate image as a runtime base. Docker build system forced me to build new image anyway, so I had no choice but to add `gdb` to base image in a better way ¯\\\_(ツ)\_/¯
3. [related system maintenance, not in PR itself] Setting `kernel.core_pattern` on the host server for core dumps to go to a predefined location (instead of that strange Ubuntu's `apport`)
4. Now also mounting `/var/crash` as a Docker volume (otherwise core dumps go inside of the container's FS)
5. Added `SYS_PTRACE` capability to `docker run` command
6. Docs
=> internal: improve server deployment

skymp5-functions-lib/src/logic/PlayerController.ts, skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts, skymp5-functions-lib/src/logic/TestUtils.ts, skymp5-functions-lib/src/mpApiInteractor.ts, skymp5-functions-lib/src/utils/persistentStorage.ts
closes #872
This should help to save round info during script hot reload.
Saved state is also used to get disconnected from active session user back to action
Added logic to cleanup rounds in warmup from disconnected users and reset round if everyone left before starting active phase
TODO: Clear round info on normal server shutdown/startup.
=> feat(skymp5-functions-lib): keep round info for SweetPie game mode in persistent storage

skymp5-functions-lib/index.ts, skymp5-functions-lib/src/logic/GameModeListener.ts, skymp5-functions-lib/src/logic/PlayerController.ts, skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts, skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts, skymp5-functions-lib/src/logic/SweetPieMap.ts, skymp5-functions-lib/src/logic/SweetPieRound.ts, skymp5-functions-lib/src/logic/TestUtils.ts, skymp5-functions-lib/src/mpApiInteractor.ts, skymp5-functions-lib/src/types/mp.d.ts, skymp5-server/cpp/addon/main.cc, skymp5-server/cpp/server_guest_lib/ActionListener.cpp, skymp5-server/cpp/server_guest_lib/MpActor.cpp, skymp5-server/cpp/server_guest_lib/MpActor.h
Added Restorer objects support.
This also introduces new API calls to get/set hp, mp and stamina for other gamemodes.
SweetPieMap description object now contains array for Restorer objects references and default time player should wait before using restorer again.
Updated round stages to start warmup counter only when player count reaches required minimum.
Also tuned other map-related logic for SweetPie game mode.
=> feat: SweetPie game mode logic update

skymp5-functions-lib/src/props/disableCheats.ts
The code for disabling console commands has been slightly refactored. The commands `modAV`, `forceAV` and `ToggleGodMode` are also disabled.
=> feat(skymp5-functions-lib): disable modAV

skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts
They were a bit out of sync, apparently. Any clean build adds this like, so...
Todo:  #949
=> internal: sync skyrim-platform definitions

skymp5-server/cpp/server_guest_lib/GetBaseActorValues.cpp
Closes #895.
Cast should probably be replaced with `fmt::underlying()` later, at the moment it is still in dev.
https://fmt.dev/dev/api.html#_CPPv4I0EN3fmt10underlyingENSt15underlying_typeI4EnumE4typeE4Enum
=> internal: update vcpkg & fix compilation error

skyrim-platform/tools/plugin-example/README.md
Make it more clear that plugins should be developed outside of Skyrim folder
=> SP Docs: Make it more clear that plugins should be developed outside of Skyrim folder

skymp5-server/cpp/papyrus_vm_lib/ActivePexInstance.cpp
Also fixes false positive warnings (return reference to stack var)
=> fix(skymp5-server): fix memory leak in ActivePexInstance

CMakeLists.txt
I have no idea why one would want to de-sync vcpkg revision in GH actions and locally.
I had a nasty bug because of this behavior. CI may just stop working randomly when vcpkg updates in github's image!!!
=> internal: use vcpkg from submodule in CI

1js/JsEngine.h
closes #266 
There were some exceptions in JsValue dtor while "printing to out of space file"
=> fix(1js): fix SP crash with debug logs enabled

docs/release/dev/sp-fix-agressor-compat.md, skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
We need to keep "agressor" version for compatibility.
This tweak was introduced in https://github.com/skyrim-multiplayer/skymp/commit/407c3c70630bc143d18a5fb9c6c49f93bc9e774e
And mistakenly removed in https://github.com/skyrim-multiplayer/skymp/commit/674e77a7efa2fb6c682f2ea861e77873a52ba791
I have no idea why one decided to do this...
=> fix(skyrim-platform): fix backward compatibility for "agressor" typo

overlay_ports/cef-prebuilt/vcpkg.json
they usually use version-semver for that 
https://github.com/microsoft/vcpkg/search?q=version-semver
=> internal: use version-semver instead of version-string in cef-prebuilt port

.github/workflows/pr-windows-ae.yml, .github/workflows/pr-windows.yml, CMakeLists.txt
Being able to choose another vcpkg installation is good, however I think it's better to remove that option for now
- There are lots of switches, it's reasonable to have not so many different setup
- It seems that GH runner implicitly exposes those vars
- We do not check minimum vcpkg version
- We do not pin dependencies versions in manifest file
Alternatives I see would be:
1. Pin versions, add vcpkg version check, clear env in runner
=> internal: remove VCPKG_ROOT/VCPKG_INSTALLATION_ROOT option

skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp, skymp5-server/cpp/server_guest_lib/MpActor.cpp, skymp5-server/cpp/server_guest_lib/MpActor.h
=> feat(skymp5-server): prevent players from using attribute regeneration potions very often 

skymp5-server/cpp/server_guest_lib/ScriptVariablesHolder.cpp, skymp5-server/cpp/server_guest_lib/ScriptVariablesHolder.h
now refr properties merge with base properties correctly
before: refr properties override base properties, removing all that was set in base but not in refr
=> fix(skymp5-server): fix Papyrus properties fill

libespm/LICENSE, savefile/LICENSE
This PR doesn't change any licensing rules. It just fixes missing licenses of savefile and libespm components (after extraction from respective bigger subprojects)
=> docs: fix missing libespm and savefile licenses

skymp5-server/cpp/server_guest_lib/ActionListener.cpp
"Это касается мельниц, воспроизвести лекго, идем в мельницу Вайтрана и пытаемся скрафтить муку, она не скрафтится и зерно вернется в инвентарь"
=> fix(skymp5-server): relax workbench base type check

skymp5-server/cpp/server_guest_lib/IPapyrusClass.h, skymp5-server/cpp/server_guest_lib/PapyrusActor.h, skymp5-server/cpp/server_guest_lib/PapyrusDebug.h, skymp5-server/cpp/server_guest_lib/PapyrusEffectShader.h, skymp5-server/cpp/server_guest_lib/PapyrusForm.h, skymp5-server/cpp/server_guest_lib/PapyrusFormList.h, skymp5-server/cpp/server_guest_lib/PapyrusGame.h, skymp5-server/cpp/server_guest_lib/PapyrusKeyword.cpp, skymp5-server/cpp/server_guest_lib/PapyrusKeyword.h, skymp5-server/cpp/server_guest_lib/PapyrusMessage.h, skymp5-server/cpp/server_guest_lib/PapyrusObjectReference.h, skymp5-server/cpp/server_guest_lib/PapyrusSkymp.h, skymp5-server/cpp/server_guest_lib/PapyrusUtility.h, skymp5-server/cpp/server_guest_lib/WorldState.cpp
=> refact(skymp5-server): remove unnecessary worldState argument passed in papyrus classes & use policy to retrieve it instead

skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp, skymp5-server/cpp/server_guest_lib/WorldState.cpp, unit/WorldStateTest.cpp
Related to ESP update.
This error prevented some users from entering the server.
=> fix(skymp5-server): do not throw on baseId anomaly

skymp5-client/src/sync/deathSystem.ts
closes #1596
This causes the player to run underwater if the spawn point is underwater
=> fix(skymp5-client): fix swimming anim after respawn

libespm/include/libespm/Type.h, libespm/src/Type.cpp
Compile error when building on release branch. Removed code causing the compile error. Project now compiles successfully.
=> internal: fix operator == and operator != compile error

skymp5-server/cpp/server_guest_lib/FormDesc.cpp, skymp5-server/cpp/server_guest_lib/FormDesc.h
---
- https://app.asana.com/0/0/1205164194490625
=> perf(skymp5-server): replace stringstream with standard C I/O functions

skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp
- Support LVLI in AddItem
- Call toGlobalId on formList members in AddItem/RemoveItem
- Filter out non-item formList members in AddItem/RemoveItem
=> fix(skymp5-server): fix ObjectReference.AddItem corner cases

skymp5-client/src/features/authModel.ts, skymp5-client/src/services/messages_http/serverManifest.ts, skymp5-client/src/services/services/frontHotReloadService.ts, skymp5-client/src/services/services/loadOrderVerificationService.ts, skymp5-client/src/services/services/remoteServer.ts, skymp5-client/src/services/services/skympClient.ts, skymp5-client/src/services/spApiInteractor.ts
- RemoteAuthGameData should be an interface, not a class. because it's being casted from plain object in code 
- We should store listeners by contsturctor itself, instead of constructor.name because in theory names can collide
- Put serverManifest in messages_http to make the contract obvious. further refactors should be done.
=> refact(skymp5-client): introduce a few refactors

overlay_triplets/x64-windows-sp.cmake, skyrim-platform/tools/dev_service/index.js, unit/DistContentsExpected.json
This is a proof of concept that forces some libs to be built and linked as DLLs instead of static libraries
In the future SP could support running embedded skymp server. In this case we wouldn't want to double-distribute the same libraries twice in the binaries.
Same for our current binaries. There is some place for skymp bundle size optimizations.
=> internal: start switching libraries to dynamic linkage (PoC)

docs/release/dev/sp-optimize-settings.md, skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.cpp
```js
var sp = skyrimPlatform;
sp.on("tick", () => {
var time = Date.now();
for (var i = 0; i < 1000; i++) {
var settings = sp.settings["skymp5-client"];
}
var timeNow = Date.now();
sp.printConsole("time passed", timeNow - time);
});
```
This benchamark now shows time passed 2-3 instead of 30-50 before
=> perf(skyrim-platform): optimize settings API

skymp5-client/src/services/services/remoteServer.ts, skymp5-client/src/services/services/spSnippetService.ts, skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp, skymp5-server/cpp/server_guest_lib/MpObjectReference.h, skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp, skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.h
- malformed base object name like "%original_name%foo" won't freeze client anymore
- setDisplayName("%original_name%") will clear display name in the server/db resulting in less traffic and less setDisplayName calls
=> fix: improve setDisplayName security & optimize

libespm/include/libespm/CombineBrowser.h, libespm/src/CombineBrowser.cpp
Now we're able to extract global ids from records (`ToGlobalId(record->GetId()`) and record fields like FormLists, ObjectReferences with base object ids, etc
=> feat(libespm): switch return type of GetDistinctRecordsByType to vector<LookupResult>

skymp5-server/cpp/server_guest_lib/database_drivers/MigrationDatabase.cpp
doesn't make much sense. however better fix warning so devs will not be annoyed
=> fix(skymp5-server): make MigrationDatabase::Upsert return 0 if terminate does nothing

skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp, skyrim-platform/src/platform_se/skyrim_platform/EventUtils.h
dangerous `CopyEventPtr` which was here since 1.6 migration in early 2022 is not a thing anymore. this was last use.
I casually tested in game by subscription to all events except `consoleMessage`
```js
events.forEach(function (eventName) {
sp.on(eventName, function (event) {
//if (eventName == 'combatState')
sp.printConsole("Event: " + eventName);
});
});
```
=> fix(skyrim-platform): fix unsafe handling of InputEvent

skymp5-client/src/services/messages/putItemMessage.ts, skymp5-client/src/services/messages/spSnippetMessage.ts, skymp5-client/src/services/messages/takeItemMessage.ts
otherwise software like our internal reserved_names_builder script may fail to process our messages source code
=> refact(skymp5-client): change type to interface in messages

cmake/scripts/generate_client_settings.cmake
- remove obsolete lobby_location setting
- set server-master-key to null in case of non-localhost ip
=> internal: improve generate_client_settings.cmake

skymp5-client/CMakeLists.txt
since https://github.com/skyrim-multiplayer/skymp/pull/1831 building skyrimPlatform.ts is not required for skymp5-client build
=> internal: remove skymp5-client target dependency on skyrim-platform target

skymp5-client/src/services/events/sendMessageWithRefrIdEvent.ts, skymp5-client/src/services/messages/activateMessage.ts, skymp5-client/src/services/messages/consoleCommandMessage.ts, skymp5-client/src/services/messages/craftItemMessage.ts, skymp5-client/src/services/messages/customPacketMessage.ts, skymp5-client/src/services/messages/refrIdMessageBase.ts, skymp5-client/src/services/services/consoleCommandsService.ts
to simplify parsing for tooling that expects `interface`
=> refact(skymp5-client): avoid unnamed types in messages

skymp5-server/cpp/server_guest_lib/ActionListener.cpp
distance must be 2 cells since it's currently max distance available in gameplay
=> fix(skymp5-server): fix inability to attack distant characters with bow/crossbow

skyrim-platform/tools/dev_service/index.js, unit/DistContentsExpected.json
Reverts skyrim-multiplayer/skymp#2316
=> feat(skyrim-platform): revert "temporary duplicate dlls in root folder"

skymp5-server/cpp/server_guest_lib/script_classes/PapyrusActor.cpp
reflecting addspell behavior. honestly, i'd rather emit it once per actor/spell pair but this adds up even more complexity
=> feat(skymp5-server): remove "already removed" warning in Actor.RemoveSpell

skyrim-platform/src/platform_se/skyrim_platform/assets/sp3.js
Convert the case of base class names to avoid issues with cases like `sslSystemLibrary` (should be `SslSystemLibrary`).
(It was @Pospelove who actually fixed the issue! I just tested it to ensure it works on Skyrim VR. 😅)
=> Fix a case sensitivity issue with base class names
